# Generated by Django 3.2.18 on 2023-02-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablebooking.reservation')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablebooking.table')),
            ],
        ),
    ]
