# Generated by Django 3.2.18 on 2023-02-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0002_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
