# Generated by Django 3.2.18 on 2023-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0005_alter_reservation_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=50),
        ),
    ]
