# Generated by Django 3.2.18 on 2023-03-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0007_remove_reservation_guest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablebooking.reservation')),
            ],
        ),
    ]
