# Generated by Django 3.2.18 on 2023-03-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0008_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
