# Generated by Django 3.2.18 on 2023-07-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0010_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_people',
            new_name='number_of_guests',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='number_of_people',
            new_name='number_of_seats',
        ),
    ]
